version: '{build} ({branch})'
skip_tags: true
image: Visual Studio 2017
init:
- cmd: git config --global core.autocrlf true
build_script:
- dotnet build
test_script:
- dotnet test "test/CVaS.UnitTests/CVaS.UnitTests.csproj"
