version: '2'

services:
  cvas.web:
    image: user/cvas.web${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80"
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq
    hostname: rmq
    ports:
      - "15672:15672"
